### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by grahampugh** [gkluoe/git2jss#18]
I'm having problems with the new version, not sure how to diagnose. The source file is not found, but it is indeed in Git. I tried both relative and full path. I also tried using `--tag`. Any ideas?:

```
$ git2jss --file "Uninstallers/Uninstall Enpass.sh" --name "Uninstall Enpass" --branch master
Running in Script mode
Remote: origin
From git@gitlab.myorg.org:mac/jamf-scripts.git
Git remote: git@gitlab.myorg.org:mac/jamf-scripts
Checked out repo at master.
Loaded Uninstall Enpass from the JSS
Cleaning up tmpdir /var/folders/7r/89m62qjn1rnf0lm0cfjj08qw0000gp/T/tmpCilYYN
Traceback (most recent call last):
  File "/usr/local/bin/git2jss", line 9, in <module>
    load_entry_point('git2jss==2.0.0', 'console_scripts', 'git2jss')()
  File "build/bdist.macosx-10.14-intel/egg/git2jss/__init__.py", line 196, in main
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 95, in __init__
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 42, in __init__
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 65, in _load_source_file
  File "build/bdist.macosx-10.14-intel/egg/git2jss/vcs.py", line 226, in get_file
  File "build/bdist.macosx-10.14-intel/egg/git2jss/vcs.py", line 208, in path_to_file
git2jss.vcs.FileNotFoundError: Couldn't find file Uninstall Enpass.sh at tag/branch master

$ git2jss --file "/Users/gpugh/sourcecode/jamf-scripts/Uninstallers/Uninstall Enpass.sh" --name "Uninstall Enpass" --branch master
Running in Script mode
Remote: origin
From git@gitlab.myorg.org:mac/jamf-scripts.git
Git remote: git@gitlab.myorg.org:mac/jamf-scripts
Checked out repo at master.
Loaded Uninstall Enpass from the JSS
Cleaning up tmpdir /var/folders/7r/89m62qjn1rnf0lm0cfjj08qw0000gp/T/tmpVHr3TM
Traceback (most recent call last):
  File "/usr/local/bin/git2jss", line 9, in <module>
    load_entry_point('git2jss==2.0.0', 'console_scripts', 'git2jss')()
  File "build/bdist.macosx-10.14-intel/egg/git2jss/__init__.py", line 196, in main
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 95, in __init__
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 42, in __init__
  File "build/bdist.macosx-10.14-intel/egg/git2jss/processors.py", line 65, in _load_source_file
  File "build/bdist.macosx-10.14-intel/egg/git2jss/vcs.py", line 226, in get_file
  File "build/bdist.macosx-10.14-intel/egg/git2jss/vcs.py", line 208, in path_to_file
git2jss.vcs.FileNotFoundError: Couldn't find file Uninstall Enpass.sh at tag/branch master
```

**Comment by geoffklee** [comment]
So to confirm: you have file that, relative to the root of the repository, exists at `Uninstallers/Uninstall Enpass.sh`, and that file is present in the HEAD commit of the master branch of that repository on the server?

I'd certainly expect your first example to work in that case. Let me see if I can reproduce the issue against our in-house gitlab here - there's probably an edge case I've missed in testing.

**Comment by grahampugh** [comment]
Yes, the file is there both locally and in the latest commit to master... Thinking out loud - do I have to do something special to specify HEAD? i.e. is `git push` not sufficient?

I did originally try the method I normally use, which is `git tag vN.N.N`; `git push --tags`; and then specify `--tag vN.N.N` in the `git2jss` command rather than `--branch master`. But that didn't work (same error message).

**Comment by geoffklee** [comment]
HEAD is just an alias for the most recent commit to the branch, so what you did should have worked, I think. I suspect there's an issue in my path parsing somewhere. Will let you know how my efforts to reproduce this go. Do you see the same error for any file in that repository, or just files in a subdirectory?

**Comment by geoffklee** [comment]
Ah, found the bug: https://github.com/gkluoe/git2jss/blob/e799c87855d5ca78be234514c707e38c24d16129/git2jss/processors.py#L65

I've mixed up processing the name of the file vs its path. The upshot is that trying to use a file that's anywhere other than the repo root will fail, I think. I'll write a test for that and fix asap. Thanks!

**Comment by grahampugh** [comment]
Thanks for the speedy fix!

**Comment by geoffklee** [comment]
Wow, this closed automatically - presumably because I said it was fixed in the commit msg! I'll reopen in case it's not fixed - any feedback appreciated. The version in pip now has the fix.

**Comment by grahampugh** [comment]
No worries - I'll test in the morning.

**Comment by grahampugh** [comment]
Hi, it's now working for me again. Thanks!

**Comment by geoffklee** [comment]
Great, thanks for the report.
